meta_title: "OphtaMiramas"
meta_description: 'Prendre rendez-vous au cabinet d'ophtalmologie des docteurs Buzzacchera Nadine et Herv√©-Fey Brigitte. Chirugie refractive, de la cataracte, traitement DMLA ...'
meta_image: "logo_ok.png" # Une image dans votre dossier app/assets/images/
