meta_title: "Ophta Miramas"
meta_description: "Prendre rendez-vous au cabinet d'ophtalmologie Ã  Miramas des docteurs Buzzacchera Nadine et docteur Soare Silvia. Chirugie refractive, cataracte, DMLA ..."
meta_image: "logo_ok.png" # Une image dans votre dossier app/assets/images/
